apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name:  ${{ values.app_name }}
  description: Hello Worldサービスです
  labels:
    app: ${{ values.app_name }}
  links:
    - url: https://${{ values.git_host_url }}/${{ values.git_owner_name }}/${{ values.git_repo_name }} 
      title: App Repository
      icon: github
  annotations:
    backstage.io/kubernetes-label-selector: 'app=${{ values.app_name }}'
    backstage.io/kubernetes-namespace: ${{ values.app_name }}
    argocd/app-selector: app.kubernetes.io/instance=${{ values.app_name }}-init
    backstage.io/techdocs-ref: url:https://${{ values.git_host_url }}/${{ values.git_owner_name }}/${{ values.git_repo_name }}
    github.com/project-slug: ${{ values.git_owner_name }}/${{ values.git_repo_name }}
spec:
  type: website
  owner: ${{ values.owner }}
  lifecycle: production
